# Generated by Django 3.2.6 on 2021-08-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='google_maps_url',
            field=models.URLField(default='https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d1970.8755484485264!2d25.117235251477243!3d60.39773333185429!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x46920089ddb0e7cb%3A0x2bd8798a34cd1bf4!2sJaakkolantie%2011%2C%2004250%20Kerava!5e0!3m2!1sfi!2sfi!4v1614347152089!5m2!1sfi!2sfi'),
            preserve_default=False,
        ),
    ]
