# Generated by Django 3.2.6 on 2022-04-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='booking_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Company name'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='facebook_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='google_maps_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='instagram_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location_postcode',
            field=models.CharField(blank=True, max_length=5, verbose_name='Postcode'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location_street_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Steet address'),
        ),
    ]
