# Generated by Django 3.2.6 on 2021-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_google_maps_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='google_maps_url',
            field=models.URLField(max_length=500),
        ),
    ]
