# Generated by Django 3.2.6 on 2022-04-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220404_1739'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='hide_content',
            field=models.BooleanField(default=False, verbose_name='Hide content'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Phone'),
        ),
    ]
