# Generated by Django 3.2.6 on 2022-04-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220404_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='show_in_navbar',
            field=models.BooleanField(default=True, verbose_name='Show in navbar'),
        ),
    ]
