# Generated by Django 3.2.6 on 2021-09-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_contact_google_maps_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='show_booking_btn',
            field=models.BooleanField(default=False, verbose_name='Show booking button'),
        ),
    ]
